# Generated by Django 4.0.4 on 2022-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='social',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
