# Generated by Django 4.0.4 on 2022-05-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0002_about_status_contact_status_news_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='delete_at',
        ),
    ]
