# Generated by Django 4.0.4 on 2022-05-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('section_image_blog', models.FileField(upload_to='')),
                ('section_blog_libele', models.CharField(max_length=255)),
                ('menu_description', models.TextField(max_length=500)),
                ('addresse', models.CharField(max_length=255)),
                ('dial_code', models.CharField(max_length=4)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('copy_right', models.TextField(max_length=500)),
                ('section_image_news', models.FileField(upload_to='')),
                ('section_description', models.TextField(max_length=500)),
            ],
        ),
    ]
