# Generated by Django 4.0.4 on 2022-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsLetter', '0002_news_created_at_news_delete_at_news_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
    ]
