# Generated by Django 4.0.4 on 2022-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created_at_contact_delete_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
