# Generated by Django 4.0.4 on 2022-05-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReseauSocial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='message',
        ),
        migrations.AddField(
            model_name='social',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='social',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='fb_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='insta_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='twitter_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
