# Generated by Django 4.0.4 on 2022-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReseauSocial', '0002_remove_social_message_social_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='social',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='social',
            name='updated_at',
        ),
    ]
