# Generated by Django 4.0.4 on 2022-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClotFovouis', '0002_fav_created_at_fav_delete_at_fav_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='updated_at',
        ),
    ]
