# Generated by Django 4.0.4 on 2022-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_created_at_menu_delete_at_menu_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='updated_at',
        ),
    ]
