# Generated by Django 4.0.4 on 2022-05-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banner', '0002_banner_created_at_banner_delete_at_banner_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated_at',
        ),
    ]
