# Generated by Django 4.0.4 on 2022-05-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platfavoris',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
