# Generated by Django 4.0.4 on 2022-05-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0002_banner_status_blog_status_menu_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='platfavoris',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='delete_at',
        ),
    ]
